### ISSUE TITLE
赛扬6305安装卡在logo页面

### ISSUE THREAD

**Issue by ycgkwyc** [openFyde/overlay-amd64-openfyde#1]
boot.msg 文件下载链接：
https://drive.google.com/file/d/1lJ32nOWb-qsRFwkJz_t2IIfweItEPxwv/view?usp=sharing

**Comment by Damenly** [comment]
boot.msg显示ui初始化有问题，麻烦再提供下 /var/log/chrome/chrome 文件以及 /var/log/ui/ui.LATEST

**Comment by ycgkwyc** [comment]
文件更新 

https://drive.google.com/drive/folders/1B_d1haLzdzzF2K3jo4Xxa5_ujrMlEVZa?usp=sharing

**Comment by Damenly** [comment]
请查看下是否有 `/usr/lib64/dri/iris_dri.so` 这个文件。

**Comment by ycgkwyc** [comment]
openfyde缺少/usr/lib64/dri/iris_dri.so  这个文件，我在整个openfyde 文件下也没有找到这个文件，尝试从fydeos v15里复制了一个iris_dri.so 文件，现在可以正常进入安装页面。

**Comment by peeweep** [comment]
iris_dri.so属于 mesa-iris 包，可以在 overlay-amd64-openfyde 的 openfyde-board-spec 中添加

``` diff   
diff --git a/virtual/openfyde-board-spec/openfyde-board-spec-0.0.7-r2.ebuild b/virtual/openfyde-board-spec/openfyde-board-spec-0.0.7-r2.ebuild
index befefdd..7b8ef04 100644
--- a/virtual/openfyde-board-spec/openfyde-board-spec-0.0.7-r2.ebuild
+++ b/virtual/openfyde-board-spec/openfyde-board-spec-0.0.7-r2.ebuild
@@ -12,6 +12,7 @@ KEYWORDS="*"
 IUSE="kernel-5_10"
 
 RDEPEND="
+    media-libs/mesa-iris
     chromeos-base/auto-expand-partition
        chromeos-base/apple-touchpad-bcm5974
     chromeos-base/amd64-openfyde-spec
```

添加后重新 build_packages、build_image

```
./build_packages --board=${BOARD} --nowithautotest --autosetgov --nouse_any_chrome
./build_image --board=${BOARD} --noenable_rootfs_verification
```

**Comment by ycgkwyc** [comment]
已解决
