### ISSUE TITLE
gclient sync 同步依赖失败

### ISSUE THREAD

**Issue by qian0jiang** [openFyde/overlay-amd64-openfyde#10]
因为无法访问google，我的depot_tools 是clone 的 https://gerrit.openfyde.cn/chromium.googlesource.com/chromium/tools/depot_tools.git
并且checkout 到 e121d14b1241 这个版本了。
但是后面gclient sync --nohooks -vvv 时会失败：
Updating depot_tools...
depot_tools update failed. Couldn't fetch main branch.
Retry later or reclone depot_tools
fatal: unable to access 'https://chromium.googlesource.com/chromium/tools/depot_tools.git/': Failed to connect to chromium.googlesource.com port 443: Connection refused
curl: (7) Failed to connect to chrome-infra-packages.appspot.com port 443: Connection refused
curl: (7) Failed to connect to chrome-infra-packages.appspot.com port 443: Connection refused
/usr/local/repo/depot_tools/bootstrap_python3: line 32: bootstrap-2@3.8.10.chromium.23_bin/python3/bin/python3: No such file or directory
curl: (7) Failed to connect to chrome-infra-packages.appspot.com port 443: Connection refused
**/usr/local/repo/depot_tools/bootstrap_python3: line 32: bootstrap-2@3.8.10.chromium.23_bin/python3/bin/python3: No such file or directory
cat: /usr/local/repo/depot_tools/python3_bin_reldir.txt: No such file or directory
/usr/local/repo/depot_tools/vpython3: line 52: /usr/local/repo/depot_tools/.cipd_bin/vpython3: No such file or directory**

**Comment by Damenly** [comment]
可以禁用掉 depot tools的auto update https://chromium.googlesource.com/chromium/tools/depot_tools.git/#updating

**Comment by qian0jiang** [comment]
禁用自动更新还是会有一样的报错：
 ~/r102/openfyde/chromium$ gclient sync --nohooks -vvv
curl: (7) Failed to connect to chrome-infra-packages.appspot.com port 443: Connection refused
/usr/local/repo/depot_tools/bootstrap_python3: line 32: bootstrap-2@3.8.10.chromium.23_bin/python3/bin/python3: No such file or directory
cat: /usr/local/repo/depot_tools/python3_bin_reldir.txt: No such file or directory
/usr/local/repo/depot_tools/vpython3: line 52: /usr/local/repo/depot_tools/.cipd_bin/vpython3: No such file or directory

**Comment by Damenly** [comment]
原因大概率还是网络问题，你能打开 chrome-infra-packages.appspot.com吗?

**Comment by qian0jiang** [comment]
我开了vpn，网页是可以打开 chrome-infra-packages.appspot.com 的，但是命令行下ping不通，我还没搞明白怎么开全局代理

**Comment by Damenly** [comment]
除此之外，gclient sync 有一部分还会fetch gs:// 这种网址。环境问题只能靠你自己摸索解决了。

**Comment by qian0jiang** [comment]
好的，非常感谢提供的帮助。
