### ISSUE TITLE
Fyde OS on Intel i7-12650H

### ISSUE THREAD

**Issue by k4k4r0tz** [openFyde/overlay-amd64-openfyde#11]
Can't install fydeos on Intel i7-12 gen laptop. I just see black screen when I select the alternate USB boot option.

**Comment by subashsn** [comment]
Hi, thanks for making this awesome OS! FydeOS works great on my 12th gen laptop, would love to get openfyde working.

Happy to contribute towards adding support for 12th gen if possible. Could you please guide on what the blocker. Thanks!

**Comment by Damenly** [comment]
> Hi, thanks for making this awesome OS! FydeOS works great on my 12th gen laptop, would love to get openfyde working.
> 
> Happy to contribute towards adding support for 12th gen if possible. Could you please guide on what the blocker. Thanks!

You can build it by yourself. Just build the [kernel](https://github.com/openFyde/project-openfyde-patches/tree/main/sys-kernel/chromeos-kernel-5_15).

**Comment by subashsn** [comment]
Will try today. Thank you!

**Comment by subashsn** [comment]
Hi, won't I need the build artefacts and configurations like this repo has for the amd64-iris platform also to be able to build the an image. Sorry if I am missing something here. Thanks

**Comment by carrie0105** [comment]
FydeOS support Intel 12 Gen chips now.
