### ISSUE TITLE
Does this work on Microsoft Surfaces?

### ISSUE THREAD

**Issue by DeveloLongScript** [openFyde/overlay-amd64-openfyde#13]
I was wondering if it does because I was interested in installing openFyde on my surface.
Thanks!

**Comment by DeveloLongScript** [comment]
I put this issue on this repo, as Surfaces use Intel CPU's.

**Comment by Damenly** [comment]
Surface series need many efforts so we do not provide overlay for Surfaces. We have put critical codes in [github](https://github.com/FydeOS-for-You-overlays). 

If you are not an opensource-enthusiast, try [FydeOS](https://fydeos.com/download/you#microsoft) (NOT AN AD).

**Comment by DeveloLongScript** [comment]
I understand how its not a ad lol
