### ISSUE TITLE
Which FydeOS or OpenFyde version to install for EOL Chromebook (ChromeOS93)?

### ISSUE THREAD

**Issue by Nyta8591** [openFyde/overlay-amd64-openfyde#18]
I have an end of life Baytrail Chromebook (KIP) that only was updated up to ChromeOS93 (https://chromebookdb.com/chromebook/hp-chromebook-14-14-ak040nr/). I am aware that the latest versions of BrunchOS wouldn’t install since in latest versions Google started using ISAs that aren’t supported on that CPU.

I couldn’t activate GAPPs on the latest FydeOS version and believe it could be the same problem as with Brunch of latest versions being incompatible with this laptop. Which version of FydeOS or OpenFyde I could try runnung pls?

**Comment by Damenly** [comment]
Even FydeOS and openFyde are downstream of chromium os, It's recommended to stay in the last supported ChromeOS since you may get unworkable sound output.
