### ISSUE TITLE
fydeos是如何实现本地账号系统的？

### ISSUE THREAD

**Issue by jwy2008** [openFyde/overlay-amd64-openfyde#2]
您好，我想在原生chromium os中加入像fydeos那样的本地账号系统，并自己编译，请问fydeos是如何实现本地账号功能的？

**Comment by nirocfz** [comment]
引入本地帐号类型的修改，主要在这几个 commit
openFyde/chromium@0b91c94d3b6b1407589fa16ee0cc6aab9d75ef2e
openFyde/chromium@90448bb83a9d491daf143e09d323a6474c34faa4
openFyde/chromium@f0e3f7da69fefb27c3080d15ec7cc9d58e6a85cd
