### ISSUE TITLE
how to add anbox or anbox-archero or waydroid to openfyde? thanks

### ISSUE THREAD

**Issue by ccchan234** [openFyde/overlay-amd64-openfyde#3]
openfyde is not too attractive unless one can easily install anbox (nailed at android 7)or anbox-archero (nailed at android 9).
would be nice if it can run waydroid (support android 12).

waydroid's author tell me that they only need the kernel module "binder" which is also needed by anbox.

thanks

**Comment by Damenly** [comment]
We have introduced ARCHERO to rock5b-openfyde and orangepi5-openfyde.

If you want porting anbox that I'm afraid you have to do it by yourself.

**Comment by ccchan234** [comment]
seems NOT for naive non programmers.

let 's close this thx
