### ISSUE TITLE
gapps stuck on accept license agreement 

### ISSUE THREAD

**Issue by ahmnabil** [openFyde/overlay-amd64-openfyde#37]
gapps stuck on accept license agreement openfyde v18
fresh install full disk
keep loading and the accept license agreement blurred out

**Comment by Lorde627** [comment]
Please send a feedback to us.
https://fydeos.io/docs/knowledge-base/recipes/feedback-howto

**Comment by NiffirgkcaJ** [comment]
> gapps stuck on accept license agreement openfyde v18 fresh install full disk keep loading and the accept license agreement blurred out

You can install GAPPS here?
