### ISSUE TITLE
borealis logs 

### ISSUE THREAD

**Issue by shifty-d** [openFyde/overlay-amd64-openfyde#5]
i'm trying to get borealis work on my machine, ye, unsupported 4 gb ram( wanna take some logs, to learn how it works, maybe it help me with setup on unsupported hardware

**Comment by peeweep** [comment]
You can search for the keyword `crosvm`/`vm_concierge` in `/var/log/messages`

**Comment by Damenly** [comment]
FYI, log provided by the user: https://imgur.com/a/F03q02C

**Comment by peeweep** [comment]
Looks like SMT not disabled and other vulnerable check not passed. Will try to skip this check next release.
