### ISSUE TITLE
构建openfyde时，在repo init 这一步报错

### ISSUE THREAD

**Issue by qian0jiang** [openFyde/overlay-amd64-openfyde#9]
按照 getting-started 文档一步步来，到repo init这一步的时候报错了：
File "/home/jiang/r102/.repo/repo/main.py", line 79
    file=sys.stderr)
我看了下报错的位置：
if sys.version_info.major < 3:
  print('repo: error: Python 2 is no longer supported; '
        'Please upgrade to Python {}.{}+.'.format(*MIN_PYTHON_VERSION_SOFT),
        file=sys.stderr)
  sys.exit(1)
按理说我安装的是python3，应该不会进入这个if才对，是我安装的python3环境不对么？
python3 -V
Python 3.6.9

**Comment by Damenly** [comment]
看下 `/usr/bin/env python3`

**Comment by Damenly** [comment]
看下` which repo `和 `repo --version `

**Comment by qian0jiang** [comment]
which repo 
/snap/bin/repo

~/r102$ repo --version
  File "/home/jiang/r102/.repo/repo/main.py", line 79
    file=sys.stderr)
        ^
SyntaxError: invalid syntax
是我安装的repo不对么

**Comment by Damenly** [comment]
是的，你按照教程上的用 https://github.com/openFyde/getting-started#install-google-depot_tools 的repo 应该就可以了。

**Comment by qian0jiang** [comment]
好的，非常感谢
